# Generated by Django 5.2.6 on 2025-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_coursecompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecompletion",
            name="certificate_id",
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
