# Generated by Django 5.2.6 on 2025-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_coursecompletion_certificate_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lessons/videos/",
                verbose_name="Видео (MP4)",
            ),
        ),
    ]
