# Generated by Django 5.2.6 on 2025-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("все", "Все"),
                            ("школьник", "Школьники"),
                            ("пенсионер", "Пенсионеры"),
                            ("МСП", "МСП"),
                        ],
                        default="все",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
