# Generated by Django 5.2.6 on 2025-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
