# Generated by Django 5.2.6 on 2025-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contact_latitude_alter_contact_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="latitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="longitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
