# Generated by Django 5.2.6 on 2025-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_is_moderator_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
