# Generated by Django 5.2.6 on 2025-10-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_documentationfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentationFile",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
