# Generated by Django 5.2.6 on 2025-10-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_eventreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='custom_title',
        ),
        migrations.AddField(
            model_name='eventreport',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
    ]
