# Generated by Django 5.2.6 on 2025-10-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_event_telegram_message_id"),
        ("core", "0011_remove_eventreport_custom_title_eventreport_comments"),
    ]

    operations = []
