# Generated by Django 5.2.6 on 2025-10-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_documentationfile_delete_event_delete_news'),
        ('core', '0012_merge_20251010_0222'),
        ('core', '0012_merge_20251010_0712'),
    ]

    operations = [
    ]
