# Generated by Django 5.2.6 on 2025-10-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_merge_20251010_0745"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramSubscriber",
        ),
    ]
