# Generated by Django 5.2.6 on 2025-10-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_merge_20251010_0944"),
        ("core", "0014_delete_telegramsubscriber"),
    ]

    operations = []
