# Generated by Django 5.2.6 on 2025-10-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_telegramsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSubscriber',
        ),
    ]
